### ISSUE TITLE
Leafy loggers should be compatible with rack / rails logger interfaces

### ISSUE THREAD

**Issue by crufia** [lookout/leafy#46]
Trying to use a leafy logger as the rack logger (eg `use Rack::CommonLogger, Leafy::Logger::Factory.get_logger 'lol'`) or as the rails logger (eg `Rails.logger = Leafy::Logger::Factory.get_logger 'lol'`) fails so that we can't use Leafy to handle request logging.

Off the bat, rails logging fails because leafy doesn't expose a formatter, and rack logging fails because leafy doesn't expose a write method. I don't know if the entire Logger interface needs to be implemented for these to work.

Rails logging works when you proxy the slf4j logger as done here: https://github.com/dekellum/rjack/blob/dev/slf4j/lib/rjack-slf4j.rb

**Comment by mkristian** [comment]
I would and implement pieces as they pop up. like the formatter in rails, etc. in the end so many gems just have their own logger implementation which makes it hard to keep.

not sure about the write method you mentioned for rack logging since http://ruby-doc.org/stdlib-2.2.2/libdoc/logger/rdoc/Logger.html does not have such a method. I probably need to look at rack ;)

**Comment by crufia** [comment]
I suspect I overstressed the importance of rack logging here (I had no idea that Rack::CommonLogger was so barbaric, and maintaining compatibility with it doesn't seem necessary). It's nice to have the rack middleware we merged so we can get logging done correctly in Sinatra or other tools that use env['rack.logger'].

FWIW, CommonLogger uses either #write or #<<. Gross.

Thanks for merging the two changes - I'll play around with them locally to make sure they're doing the right thing with my projects.
